#include <stdio.h>
#include <exception>
using namespace std;

void myunex()
{
	puts("발생해서는 안 되는 에러 발생");
	exit(-2);
}

void calc() throw(int)
{
	throw "string";

}



int main()
{
	set_terminate(myunex);
	try
	{
		calc();
	}
	catch (int a)
	{
		puts("정수형 예외 발생");
	}

	puts("프로그램 종료");
	return 0;
}